FROM edwinbosveld/alpine-maven-git:3.5-jdk-8
WORKDIR /app
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
WORKDIR /app/boxfuse-sample-java-war-hello/
RUN mvn package &&\
    cp /app/boxfuse-sample-java-war-hello/target/*.war /app