---
version: "3"

services:
    maven:
        build:
            context: dockerfiles/
        volumes:
            - mvn_volume:/app

    tomcat:
        image: informex/alpine-tomcat:latest
        ports:
            - "8080:8080"
        volumes:
            - mvn_volume:/opt/tomcat/webapps
        depends_on:
            - maven
            
volumes:
    mvn_volume:

networks:
    default: