---
version: "3"

services:
    maven:
        build:
            context: ./dockerfiles
            dockerfile: maven.dockerfile
        volumes:
            - mvn_volume:/boxfuse-sample-java-war-hello

    tomcat:
        image: informex/alpine-tomcat:latest
        ports:
            - "8080:8080"
        volumes:
            - mvn_volume:/opt/tomcat/webapps
        depends_on:
            - maven
            
volumes:
    mvn_volume: