FROM openjdk:8u151-stretch

# Install packages
RUN apt update

# Install docker 18.03
RUN apt install apt-transport-https ca-certificates curl software-properties-common
RUN -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
RUN apt update
RUN apt install docker-ce

# Clear cache
RUN apt clean