---
- name: Configuring the master node
  hosts: master
  become: true
  gather_facts: false

  tasks:
    - name: Install maven
      apt:
        name: maven
        state: latest

    - name: Clone a app from github repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/tryam/
        clone: true
        update: true

    - name: Build application
      command:
        chdir: /tmp/tryam/
        cmd: mvn package

- name: Configuring the slave node
  hosts: slave
  become: true
  gather_facts: false

  tasks:
    - name: Install tomcat
      apt:
        name: tomcat9
        state: latest

    - name: Moving an artifact
      synchronize:
        src: /tmp/tryam/target/
        dest: /var/lib/tomcat9/webapps/
      delegate_to: master